# Generated by Django 6.0.3 on 2026-09-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificaciones', models.TextField(help_text='Detalles técnicos, dimensiones, peso, consumo eléctrico, etc.')),
                ('manual_usuario_url', models.URLField(blank=True, help_text='Enlace al manual o documentación digital', max_length=255, null=True)),
                ('norma_certificacion', models.CharField(blank=True, help_text='Ejemplo: ISO 9001, CE, RoHS, etc.', max_length=100, null=True)),
                ('fecha_revision', models.DateField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='inventario.producto')),
            ],
        ),
    ]
